// Generated by dts-bundle v0.7.3

import 'focus-visible/dist/focus-visible.min';
import './index.sass';
export default class StakingSDK {
    constructor(config: Config);
    on(event: 'stake' | 'unstake' | 'claim', listener: (...args: any[]) => void): import("events").EventEmitter;
    open(coins: UserCoin[]): void;
    close(): void;
}

export interface Config {
    id: string;
    theme?: Theme;
}
export interface Theme {
    colorPrimary: string;
    colorPrimaryDark: string;
    colorAccent: string;
    windowBackground: string;
    detailsHeaderBg: string;
    focusColor: string;
    colorGreen: string;
    warningColor: string;
}
export interface UserCoin {
    symbol: string;
    address: string;
    balance: string;
}
export class EventData {
    symbol: string;
    amount: string;
    validatorName: string;
    validatorAddress: string;
    type: Event;
    constructor(symbol: string, amount: string, validatorName: string, validatorAddress: string, type: Event);
}
export type Event = 'stake' | 'unstake' | 'claim';

